name: Cucumber Tests

on:
   push:
      branches: [working-test, main, working_test_pipeline]
   pull_request:
      branches: [working-test, main, working_test_pipeline]

jobs:
   api-tests:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"
              cache: "npm"

         - name: Setup Java
           uses: actions/setup-java@v3
           with:
              java-version: "17"
              distribution: "temurin"

         - name: Install dependencies
           run: |
              npm ci
              npx playwright install --with-deps

         - name: Start API Server
           run: |
              nohup java -jar ./src/api/demo-0.0.1-SNAPSHOT.jar &
              sleep 30

         - name: Run API Tests
           run: |
               npm run test:fetchEmptyBooks || true;
               npm run test:createBook || true;
               npm run test:createBookIdAsNumber || true;
               npm run test:createBookIdAsString || true;
               npm run test:createDuplicateBook || true;
               npm run test:fetchAllBooks || true;
               npm run test:getBookById || true;
               npm run test:duplicateAndIdValidationSteps || true;
               npm run test:UpdateBookRecord || true;
               npm run test:DeleteBook || true;
              

         - name: Upload API Test Results
           if: always()
           uses: actions/upload-artifact@v3
           with:
              name: api-test-results
              path: |
                 allure-results/
                 reports/cucumber-report.html

   ui-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"
              cache: "npm"

         - name: Install dependencies
           run: |
              npm ci
              npx playwright install --with-deps

         - name: Run UI Tests
           run: |
              npm run test:addEmployee || true;
              npm run test:searchEmployee || true;
              npm run test:deleteEmployee || true;
              npm run test:UpdateUserPersonalDetails || true;
              npm run test:viewUserInfo || true;
              npm run test:createTextPost || true;
              npm run test:editTextPost || true;
              npm run test:deleteTextPost || true;
              npm run test:addCandidate || true;
              npm run test:searchCandidate || true;
              npm run test:deleteCandidate || true;
              npm run test:employeeClaims || true;
              npm run test:assignClaim || true;
              npm run test:submitClaim || true;
              npm run test:applyLeave || true;
              npm run test:assignLeave || true;
              npm run test:addKPI || true;
              npm run test:deleteKPI || true;
              npm run test:cancelAddKPI || true;

         - name: Upload UI Test Results
           if: always()
           uses: actions/upload-artifact@v3
           with:
              name: ui-test-results
              path: |
                 allure-results/
                 reports/cucumber-report.html

   generate-report:
      needs: [api-tests, ui-tests]
      runs-on: ubuntu-latest
      if: always()
      steps:
         - uses: actions/checkout@v4

         - name: Download API Test Results
           uses: actions/download-artifact@v3
           with:
              name: api-test-results
              path: api-results

         - name: Download UI Test Results
           uses: actions/download-artifact@v3
           with:
              name: ui-test-results
              path: ui-results

         - name: Generate Combined Report
           run: |
              npm install -g allure-commandline
              mkdir -p combined-results
              cp -r api-results/allure-results/* combined-results/ || true
              cp -r ui-results/allure-results/* combined-results/ || true
              allure generate combined-results -o allure-report --clean

         - name: Upload Combined Report
           uses: actions/upload-artifact@v3
           with:
              name: test-report
              path: |
                 allure-report/
                 api-results/reports/cucumber-report.html
                 ui-results/reports/cucumber-report.html
              retention-days: 30

         - name: Deploy Allure Report to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: allure-report/

            